services:
    nginx:
        image: nginx
        restart: always
        ports:
            - "5080:80"
        depends_on:
            - php
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./:/var/www/html:delegated"
        container_name: "containerized-app-nginx"
    php:
        build:
            context: docker/php
        restart: always
        depends_on:
            - pgsql
        volumes:
            - "./:/var/www/html:delegated"
            - "./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
        container_name: "containerized-app-php"
    php-cli:
        build:
            context: docker/php-cli
        volumes:
            - "./:/var/www/html:delegated"
            - "./docker/php-cli/php.ini:/usr/local/etc/php/php.ini"
        container_name: "containerized-app-php-cli"
    pgsql:
        image: postgres:15.2
        container_name: pgsql
        restart: unless-stopped
        ports:
            - "5032:5432"
        volumes:
            - "/var/lib/pgsql"
            - "./docker/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql"
        environment:
            POSTGRES_DATABASE: "db_app"
            POSTGRES_USER: "db_app"
            POSTGRES_PASSWORD: "secret"
            POSTGRES_ROOT_PASSWORD: "secret"
